### ISSUE TITLE
Support for AzureUSGovernmentCloud

### ISSUE THREAD

**Issue by scabana** [virtual-kubelet/azure-aci#29]
Current implementation doesn't support us gov (https://github.com/virtual-kubelet/azure-aci/blob/c80d51a382a42db9da87b4207789a279a55ed90b/aci.go#L181-L183). Are there plans to support it? Container instances seems to be available in us gov now.

**Comment by ibabou** [comment]
@scabana yeah, currently the support is only for public azure, but this was since ACI didn't support any. Let me add this to be tracked by our team, we should work on having this supported in near future (maybe by Jan-Feb time range). +@macolso

**Comment by scabana** [comment]
@ibabou Thanks for the quick reply. In the mean time, do you think it's possible to set it up in a way to have ACI in PublicCloud and AKS in us gov?

**Comment by ibabou** [comment]
@scabana this probably won't work (at least in a non hacky way), unless modifications are made to VK impl. because now the ACI resources will need to land into a different subscription in public cloud. Today the subscription/resourcegroup/client_secret is all obtained from current AKS cluster. One way could be to create your own spec for deploying vk that mounts a config acting like azure.json but have information to access this other public cloud subscription (as if the cluster is there), and set/pass a secret for the SP specified in this mock config. But again this means it still won't work properly, as you can't setup it for byovnet (vnets needs to be used within same region) support, and so created pods won't be able to access workloads in the cluster, or discover the services clusterIPs. I'd suggest waiting till it is officially supported.

**Comment by scabana** [comment]
Hi, thanks a lot! This will be helpful.
